language: node_js
node_js:
  - "10.16.0"
script:
# - npm test
 - npm run build
# deploy:
#   provider: firebase
#   token:
#     secure: "gfZLu4u0mxSwBLVldpeimj0Vank5eXJTi4dq8NylDwLtkzzOA2uPyj/FqjBXDRf+8wkwKsyYrVQ61r39JM+PusXXJA65eL88p4nwxsdsIs3ibW4btsG9KzOj3+TaUpEkmLteC4y4wQRckEO5ciQDGDVJxBbEX6RJ7Gs4yTxtqBweNAhc3PnK6kTf2sMkS3AgOBqdDLjPC0UBs8klxXo8EPXV8LOISm2oqt9+FfeO/dXQt7/s9SR77nh+c8xR4DEauk3Cu9rojdisgRO2Iy/6rQFRhofA7Y3HyFCw84VzIHib88m3qt8CYfMVd7jBhpV4mv0TDzaJjSXvykBSXGuOHhqkYhHfhXITnoAXVwHQ20dEVyNPhvWd+ddfY3N0hwHf7xpLsyqG1P1jjWiVRn0bxmhmvTbKzDNIebcdSWpkeua4cPip76kQI0blD+DydbbNErJNr2LSjMrC7oW+7Vp9sKVXhVtsYsIz6ftLa/J7ghrG2H6LS2T/5aqDcOxyH54X4Ve2fSbp0wULbsFn80uVAsLkcFacB2k2lWHHs4+uKBy5wMvuAsuiryDDhb4TU/FAq7eqxE8oXILVdzqkazvekqRUHB/EhFnakX+vafhB3Fwd6UlACSl3qGkTq+IT7uRLX3kElHYcjc5ezgCpnZkxXDbTpqkEu2B9ynbiUaMPIxQ="
